[app]

# (title) اسم التطبيق اللي هيظهر للمستخدم
title = Yusr Lite

# (package.name) اسم الحزمة (بدون مسافات)
package.name = yusrlite

# (package.domain) النطاق الخاص بك
package.domain = org.yusr.lite

# (source.dir) مكان الكود (النقطة تعني المجلد الحالي)
source.dir = .

# (source.include_exts) الملفات اللي هتدخل في الـ APK
source.include_exts = py,png,jpg,ttf,json,db

# (version) رقم الإصدار (اللي كان عامل المشكلة!)
version = 0.1

# (requirements) المكتبات المطلوبة للتشغيل
requirements = python3,kivy==2.3.0,arabic-reshaper,python-bidi

# (orientation) وضع الشاشة
orientation = portrait

# (fullscreen) ملء الشاشة
fullscreen = 1

# --- إعدادات الأندرويد الضرورية ---
android.api = 33
android.minapi = 21
android.ndk = 25b
android.archs = arm64-v8a, armeabi-v7a
android.accept_sdk_license = True

# (log_level) عشان نشوف التفاصيل لو حصلت مشكلة
log_level = 2

[buildozer]
warn_on_root = 1
