name: Build Yusr Lite APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libgstreamer1.0-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev portaudio19-dev libportaudio2
          sudo apt-get install -y libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev autopoint libltdl-dev
          pip install --upgrade pip
          # تحديث Cython ليتوافق مع Kivy 2.3.1
          pip install setuptools wheel "Cython>=3.0.0" buildozer kivy

      - name: Build with Buildozer
        run: |
          # 1. تجهيز ملف التشغيل الصحيح (استخدام نسخة الموبايل)
          if [ -f "main_mobile.py" ]; then
            mv main.py main_desktop_backup.py || true
            cp main_mobile.py main.py
          fi
          
          # 2. البناء (تم تفعيل قبول التراخيص في buildozer.spec)
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Yusr-Lite-Package
          path: bin/*.apk
