name: Build Yusr Lite APK
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python_version: '3.11'

      - name: Install Buildozer and Dependencies
        run: |
          sudo apt update
          # غيرنا libtinfo5 لـ libtinfo6 هنا عشان يرضى يشتغل
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip install --user --upgrade buildozer Cython==0.29.33

      - name: Build APK with Buildozer
        run: |
          # السطر ده بيوافق على الرخص وبيبدأ البناء
          yes | buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Yusr-Lite-Package
          path: bin/*.apk
